services:
  backup-monitor:
    build:
      context: .
    container_name: nextcloud-backup-monitor
    restart: unless-stopped
    environment:
      - PUSHPLUS_TOKEN=${PUSHPLUS_TOKEN}
      - PUSHPLUS_TOPIC=${PUSHPLUS_TOPIC}
      - DOCKER_CONTAINER=${DOCKER_CONTAINER}
      - RUN_ON_START=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro